[package]
name = "libunftp"
version = "0.17.3"
authors = [
    "Agoston Horvath <ahorvath@bol.com>",
    "Dávid Kosztka <dkosztka@bol.com>",
    "Hannes de Jager <hdejager@bol.com>",
    "Koen Wilde <koen@chillheid.nl>",
    "Maarten Dirkse <mdirkse@bol.com>",
    "Steven Meunier <smeunier@bol.com>",
    "Rob klein Gunnewiek <rkleingunnewiek@bol.com>",
   ]
description = "Extensible, async, cloud orientated FTP(S) server library."
documentation = "https://docs.rs/libunftp/"
repository = "https://github.com/bolcom/libunftp"
license = "Apache-2.0"
readme = "README.md"
keywords = ["ftp", "ftps"]
categories = ["network-programming"]
edition = "2018"

[workspace]

members = [
    "crates/unftp-auth-jsonfile",
    "crates/unftp-auth-pam",
    "crates/unftp-auth-rest",
    "crates/unftp-sbe-fs",
    "crates/unftp-sbe-gcs"
]

[dependencies]
async-trait = "0.1.50"
bitflags = "1.2.1"
bytes = "1.0.1"
chrono = {version = "0.4.19", features = ["serde"]}
derive_more = { version = "0.99.13", features = ["display"] }
futures = {version = "0.3.14", features = ["std"]}
itertools = "0.10.0"
lazy_static = "1.4.0"
moka = "0.3.0"
prometheus = "0.12.0"
proxy-protocol = "0.3.0"
rand = "0.8.3"
rustls = "0.19.1"
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_info"] }
slog-stdlog = "4.1.0"
thiserror = "1.0.24"
tokio = { version = "1.5.0", features = ["rt", "net", "sync", "io-util", "macros", "time", "fs"]}
tokio-stream = "0.1.5"
tokio-rustls = { version = "0.22.0" }
tokio-util = { version = "0.6.6", features=["codec", "compat"] }
tracing = "0.1.25"
tracing-attributes = "0.1.15"
tracing-futures = { version = "0.2.5", features = ["std", "std-future", "futures-03"]}
uuid = { version = "0.8.2", features = ["v4"] }
rust-crypto = "^0.2"
encoding = "0.2.33"

[dev-dependencies]
pretty_assertions = "0.7.1"
tokio = { version = "1.5.0", features = ["rt-multi-thread"]}
unftp-sbe-fs = { path = "../libunftp/crates/unftp-sbe-fs"}
